site_name: Expense Ease
site_url: https://sitename.example
theme:
  name: material
  features:
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - content.code.copy
  font:
    text: Outfit
    code: Roboto Mono
  palette:
  # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
    # # Dark Mode
    # - scheme: slate
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Dark mode
    #   primary: black
    #   accent: white

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - markdown.extensions.abbr
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Functional Doc: functional.md
  - Workflow: workflow.md
  - Technical Doc: technical.md
  - CI/CD Pipeline and Deployment Flow: deploy.md
  - Use Case Doc: usecase.md
  - Testing:
    - Testing Module: test-cases.md
  - UI UX: ui_ux.md
  
extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js